### ISSUE TITLE
java.lang.AbstractMethodError: Method me/codexadrian/spirit/compat/rei/categories/SoulEngulfingCategory$1.method_25396()Ljava/util/List; is abstract

### ISSUE THREAD

**Issue by TheButterbrotMan** [Toadstool-Studios/Spirit#25] opened 2022-07-31 05:04 UTC
https://bytebin.lucko.me/AOxoIkPXxr

**Comment by CodexAdrian** [comment] 2022-08-03 15:58
I cant seem to replicate this on just regular spirit + rei on fabric. Maybe its another mod causing this issue?

**Comment by CodexAdrian** [comment] 2022-08-03 15:59
Oh this is also a duplicate of #23

**Closed as completed by CodexAdrian** 2022-08-03 15:59 UTC
